### ISSUE TITLE
[BUG] Panic core_esp8266_main.cpp:137 __yield

### ISSUE THREAD

**Issue by emign** [ayushsharma82/AsyncElegantOTA#102]
**Describe the bug**
After the update has finished, the esp8266 (NodeMCU 12E) crashed with this exception

`User exception (panic/abort/assert)
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Panic core_esp8266_main.cpp:137 __yield

>>>stack>>>

ctx: sys
sp: 3ffffcf0 end: 3fffffb0 offset: 0000
3ffffcf0:  3ffffd1c 3ffe8ff8 3ffffd10 4020cfa4  
3ffffd00:  000000fe 00000000 00000000 00000000  
3ffffd10:  00000000 00000000 00000000 3fff3278  
3ffffd20:  00000000 00000000 00000008 4020cfa4  
3ffffd30:  3fff9544 3fff7d00 3fff8e5c 4021ffde  
3ffffd40:  3fff9544 00000001 3fff8e5c 4022004b  
3ffffd50:  3fff9544 00000020 3fff90cc 4021fab5  
3ffffd60:  3ffffd80 3fff7d00 3ffffd80 4021a145  
3ffffd70:  3fff9544 3fff7d00 3fff8e5c 4021a258  
3ffffd80:  00000000 001b001f 00000000 00000000  
3ffffd90:  3fff0065 00000000 3fff8aa0 4025e120  
3ffffda0:  00000001 2c9f0300 4000050c 000001df  
3ffffdb0:  000001df 3fff962a 3fff8e5c 4020e1d1  
3ffffdc0:  3fff8e5c 00000030 0000001c ffffffff  
3ffffdd0:  4025fcf4 0000ffff 000000e0 000001de  
3ffffde0:  000001df 3fff962a 3fff8e5c 4020c3a8  
3ffffdf0:  00000000 4bc6a7f0 83958106 0095c010  
3ffffe00:  00000000 00000000 4bc6a7f0 00000000  
3ffffe10:  000001de 00000001 401007d1 00000000  
3ffffe20:  00008183 3fff8cfc 3fff8a9c 3fff95e4  
3ffffe30:  3ffffe90 3fff8d74 3fff8a9c 4020c3fc  
3ffffe40:  3ffffe90 3fff8d74 3fff8a9c 40222df8  
3ffffe50:  000001df 3fff962a 3fff8d74 3fff8e5c  
3ffffe60:  00000000 00000000 3fff8a9c 4025a050  
3ffffe70:  3fff000a 3fff8a9c 3fff3ab5 00000000  
3ffffe80:  3fff95e4 3fff8a9c 3fff8d74 40222e58  
3ffffe90:  3fff8a58 3fff8a4c 00000001 3fff3664  
3ffffea0:  3fff38e4 3fff3664 3fff95e4 3fff3ab0  
3ffffeb0:  3fff8a9c 3fff3ab4 3fff3ab5 40260779  
3ffffec0:  00001000 3fffc6fc 0000005c 3fffdab0  
3ffffed0:  00000018 00000000 3ffe88c8 00000000  
3ffffee0:  3fff0000 00000215 00000020 3fff3664  
3ffffef0:  3fff38e4 3fff9602 3fff95e4 4025df01  
3fffff00:  00000014 3fff3664 3ffe88c8 40100f43  
3fffff10:  00000000 3fff5e14 3ffef188 3fff6bfc  
3fffff20:  3fffdc80 00000020 3fff8a34 3
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

0x4020cfa4 in AsyncWebServerResponse::addHeader(String const&, String const&) at ??:?
0x4020cfa4 in AsyncWebServerResponse::addHeader(String const&, String const&) at ??:?
0x4021ffde in raise_exception at core_esp8266_postmortem.cpp:?
0x4022004b in __panic_func at ??:?
0x4021fab5 in yield at ??:?
0x4021a145 in AsyncElegantOtaClass::restart() at ??:?
0x4021a258 in std::_Function_handler<void (AsyncWebServerRequest*), AsyncElegantOtaClass::begin(AsyncWebServer*, char const*, char const*)::{lambda(AsyncWebServerRequest*)#3}>::_M_invoke(std::_Any_data const&, AsyncWebServerRequest*&&) at AsyncElegantOTA.cpp:?
0x4025e120 in ip4_output_if_opt_src at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/ipv4/ip4.c:1765
0x4020e1d1 in AsyncCallbackWebHandler::handleRequest(AsyncWebServerRequest*) at ??:?
0x4025fcf4 in tcp_input at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/tcp_in.c:153
0x4020c3a8 in AsyncWebServerRequest::_onData(void*, unsigned int) at ??:?
0x401007d1 in millis at ??:?
0x4020c3fc in std::_Function_handler<void (void*, AsyncClient*, void*, unsigned int), AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*)::{lambda(void*, AsyncClient*, void*, unsigned int)#8}>::_M_invoke(std::_Any_data const&, void*&&, AsyncClient*&&, std::_Any_data const&, unsigned int&&) at WebRequest.cpp:?
0x40222df8 in AsyncClient::_recv(std::shared_ptr<ACErrorTracker>&, tcp_pcb*, pbuf*, long) at ??:?
0x4025a050 in tcp_send_empty_ack at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/tcp_out.c:2058
0x40222e58 in AsyncClient::_s_recv(void*, tcp_pcb*, pbuf*, long) at ??:?
0x40260779 in tcp_input at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/tcp_in.c:501 (discriminator 1)
0x4025df01 in ip4_input at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/ipv4/ip4.c:1467
0x40100f43 in umm_free_core at umm_malloc.cpp:?

Panic core_esp8266_main.cpp:137 __yield

>>>stack>>>

ctx: sys
sp: 3ffffa20 end: 3fffffb0 offset: 0000
3ffffa20:  40295131 00000000 3ffffa80 4022c0e4  
3ffffa30:  000000fe 00000000 00000000 00000000  
3ffffa40:  00000000 00000000 00000000 40231aac  
3ffffa50:  00000000 40295131 00000001 00002200  
3ffffa60:  3fffc200 40103650 04000000 4010202a  
3ffffa70:  00000003 00000004 40003b4d 00000000  
3ffffa80:  00000000 00000000 00000000 40103636  
3ffffa90:  401036ad 00000031 40302063 00000000  
3ffffaa0:  00000000 00000000 00000000 00000004  
3ffffab0:  40003b53 2c9f0300 4000050c 3fffc278  
3ffffac0:  40103650 3fffc200 00000022 40231aac  
3ffffad0:  40003b4d 00000030 00000010 ffffffff  
3ffffae0:  40001ddc 00000066 00018000 00000000  
3ffffaf0:  00ff0000 5ffffe00 5ffffe00 00000000  
3ffffb00:  00018000 00000000 3ffffac3 3ffffc08  
3ffffb10:  00000020 0000003c 3fffffb0 00000030  
3ffffb20:  0000003c 3ffe83c4 000000a0 4022f069  
3ffffb30:  3ffffc11 00000001 0000006e ffff0208  
3ffffb40:  3ffffbe0 0000009f 4020cfa4 3fff4cd0  
3ffffb50:  3fffffb0 3ffe83c4 000000a0 4022f069  
3ffffb60:  3ffffc38 00000000 00000077 ffff0208  
3ffffb70:  3ffffc10 0000009f 4010392e 00000100  
3ffffb80:  3ffebfdc 7fffffff 00002200 00000001  
3ffffb90:  00000001 00000080 00000000 4020cfa4  
3ffffba0:  3ffebfdc 00000020 3ffffbe0 4022f0a5  
3ffffbb0:  3ffffca0 3ffffc90 00000004 3fffc278  
3ffffbc0:  40103650 3fffc200 00000022 4022f0a5  
3ffffbd0:  4021fcc1 3ffffcf0 3ffffc10 4021fcb4  
3ffffbe0:  66666633 30326666 3320203a 64666666  
3ffffbf0:  20303863 30303030 30323030 66663320  
3ffffc00:  33613866 66332034 62366666 20206366  
3ffffc10:  203a000a 66666633 30666366 646e6520  
3ffffc20:  6633203a 66666666 6f203062 65736666  
3ffffc30:  30203a74 0a303030 00000000 4010114c  
3ffffc40:  3ffffca0 3ffffca0 00000008 00000000  
3ffffc50:  4021fcc1 0000017b 3fff8a9c 4021fcb4  
3ffffc60:  6573550a 78652072 74706563 206e6f69  
3ffffc70:  6e617028 612f6369 74726f62 7373612f  
3ffffc80:  3ffffca0 3ffffc90 00000004 00000000  
3ffffc90:  00000001 3fffff20 3fffdc80 00000020  
3ffffca0:  3fff8a34 3fff6bfc 00000004 40100f43  
3ffffcb0:  3ffffcd0 3ffffcc0 3fffff30 4021fd0e  
3ffffcc0:  00000020 3ffffcf0 3fffffb0 00000000  
3ffffcd0:  5ffffe00 5ffffe00 0000000f 3fff4cd0  
3ffffce0:  3fffffb0 3ffffcf0 3ffffcf0 4021ff6e <
3ffffcf0:  3ffffd1c 3ffe8ff8 3ffffd10 4020cfa4  
3ffffd00:  000000fe 00000000 00000000 00000000  
3ffffd10:  00000000 00000000 00000000 3fff3278  
3ffffd20:  00000000 00000000 00000008 4020cfa4  
3ffffd30:  3fff9544 3fff7d00 3fff8e5c 4021ffde  
3ffffd40:  3fff9544 00000001 3fff8e5c 4022004b  
3ffffd50:  3fff9544 00000020 3fff90cc 4021fab5  
3ffffd60:  3ffffd80 3fff7d00 3ffffd80 4021a145  
3ffffd70:  3fff9544 3fff7d00 3fff8e5c 4021a258  
3ffffd80:  00000000 001b001f 00000000 00000000  
3ffffd90:  3fff0065 00000000 3fff8aa0 4025e120  
3ffffda0:  00000001 2c9f0300 4000050c 000001df  
3ffffdb0:  000001df 3fff962a 3fff8e5c 4020e1d1  
3ffffdc0:  3fff8e5c 00000030 0000001c ffffffff  
3ffffdd0:  4025fcf4 0000ffff 000000e0 000001de  
3ffffde0:  000001df 3fff962a 3fff8e5c 4020c3a8  
3ffffdf0:  00000000 4bc6a7f0 83958106 0095c010  
3ffffe00:  00000000 00000000 4bc6a7f0 00000000  
3ffffe10:  000001de 00000001 401007d1 00000000  
3ffffe20:  00008183 3fff8cfc 3fff8a9c 3fff95e4  
3ffffe30:  3ffffe90 3fff8d74 3fff8a9c 4020c3fc  
3ffffe40:  3ffffe90 3fff8d74 3fff8a9c 40222df8  
3ffffe50:  000001df 3fff962a 3fff8d74 3fff8e5c  
3ffffe60:  00000000 00000000 3fff8a9c 4025a050  
3ffffe70:  3fff000a 3fff8a9c 3fff3ab5 00000000  
3ffffe80:  3fff95e4 3fff8a9c 3fff8d74 40222e58  
3ffffe90:  3fff8a58 3fff8a4c 00000001 3fff3664  
3ffffea0:  3fff38e4 3fff3664 3fff95e4 3fff3ab0  
3ffffeb0:  3fff8a9c 3fff3ab4 3fff3ab5 40260779  
3ffffec0:  00001000 3fffc6fc 0000005c 3fffdab0  
3ffffed0:  00000018 00000000 3ffe88c8 00000000  
3ffffee0:  3fff0000 00000215 00000020 3fff3664  
3ffffef0:  3fff38e4 3fff9602 3fff95e4 4025df01  
3fffff00:  00000014 3fff3664 3ffe88c8 40100f43  
3fffff10:  00000000 3fff5e14 3ffef188 3fff6bfc  
3fffff20:  3fffdc80 00000020 3fff8a34 3fff6bfc  
3fffff30:  3fff3664 00000008 3fff95e4 40256965  
3fffff40:  3fffdc80 3fff60bc 3fff8a34 40256764  
3fffff50:  402845e5 3fff60bc 3fff8a34 402845f7  
3fffff60:  3fff95f4 3fff95e4 00000000 3fffdcc0  
3fffff70:  4027b7a6 00000000 3fff8a34 4027fe37  
3fffff80:  40000f49 3fffdab0 3fffdab0 40000f49  
3fffff90:  40000e19 000a184c 00000000 00000005  
3fffffa0:  00000000 aa55aa55 0000008a 40105aa5  
<<<stack<<<

0x40295131 in etharp_output at ??:?
0x4022c0e4 in _printf_i at /workdir/repo/newlib/newlib/libc/stdio/nano-vfprintf_i.c:246
0x40231aac in __ssputs_r at /workdir/repo/newlib/newlib/libc/stdio/nano-vfprintf.c:232
0x40295131 in etharp_output at ??:?
0x40103650 in wDev_ProcessFiq at ??:?
0x4010202a in pp_soft_wdt_feed_local at ??:?
0x40103636 in wDev_MacTim1Arm at ??:?
0x401036ad in wDev_ProcessFiq at ??:?
0x40103650 in wDev_ProcessFiq at ??:?
0x40231aac in __ssputs_r at /workdir/repo/newlib/newlib/libc/stdio/nano-vfprintf.c:232
0x4022f069 in _vsnprintf_r at /workdir/repo/newlib/newlib/libc/stdio/vsnprintf.c:71 (discriminator 4)
0x4020cfa4 in AsyncWebServerResponse::addHeader(String const&, String const&) at ??:?
0x4022f069 in _vsnprintf_r at /workdir/repo/newlib/newlib/libc/stdio/vsnprintf.c:71 (discriminator 4)
0x4010392e in wDev_ProcessFiq at ??:?
0x4020cfa4 in AsyncWebServerResponse::addHeader(String const&, String const&) at ??:?
0x4022f0a5 in vsnprintf at /workdir/repo/newlib/newlib/libc/stdio/vsnprintf.c:41
0x40103650 in wDev_ProcessFiq at ??:?
0x4022f0a5 in vsnprintf at /workdir/repo/newlib/newlib/libc/stdio/vsnprintf.c:41
0x4021fcc1 in ets_printf_P at core_esp8266_postmortem.cpp:?
0x4021fcb4 in ets_printf_P at core_esp8266_postmortem.cpp:?
0x4010114c in malloc at ??:?
0x4021fcc1 in ets_printf_P at core_esp8266_postmortem.cpp:?
0x4021fcb4 in ets_printf_P at core_esp8266_postmortem.cpp:?
0x40100f43 in umm_free_core at umm_malloc.cpp:?
0x4021fd0e in print_stack at core_esp8266_postmortem.cpp:?
0x4020cfa4 in AsyncWebServerResponse::addHeader(String const&, String const&) at ??:?
0x4020cfa4 in AsyncWebServerResponse::addHeader(String const&, String const&) at ??:?
0x4021ffde in raise_exception at core_esp8266_postmortem.cpp:?
0x4022004b in __panic_func at ??:?
0x4021fab5 in yield at ??:?
0x4021a145 in AsyncElegantOtaClass::restart() at ??:?
0x4021a258 in std::_Function_handler<void (AsyncWebServerRequest*), AsyncElegantOtaClass::begin(AsyncWebServer*, char const*, char const*)::{lambda(AsyncWebServerRequest*)#3}>::_M_invoke(std::_Any_data const&, AsyncWebServerRequest*&&) at AsyncElegantOTA.cpp:?
0x4025e120 in ip4_output_if_opt_src at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/ipv4/ip4.c:1765
0x4020e1d1 in AsyncCallbackWebHandler::handleRequest(AsyncWebServerRequest*) at ??:?
0x4025fcf4 in tcp_input at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/tcp_in.c:153
0x4020c3a8 in AsyncWebServerRequest::_onData(void*, unsigned int) at ??:?
0x401007d1 in millis at ??:?
0x4020c3fc in std::_Function_handler<void (void*, AsyncClient*, void*, unsigned int), AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*)::{lambda(void*, AsyncClient*, void*, unsigned int)#8}>::_M_invoke(std::_Any_data const&, void*&&, AsyncClient*&&, std::_Any_data const&, unsigned int&&) at WebRequest.cpp:?
0x40222df8 in AsyncClient::_recv(std::shared_ptr<ACErrorTracker>&, tcp_pcb*, pbuf*, long) at ??:?
0x4025a050 in tcp_send_empty_ack at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/tcp_out.c:2058
0x40222e58 in AsyncClient::_s_recv(void*, tcp_pcb*, pbuf*, long) at ??:?
0x40260779 in tcp_input at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/tcp_in.c:501 (discriminator 1)
0x4025df01 in ip4_input at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/core/ipv4/ip4.c:1467
0x40100f43 in umm_free_core at umm_malloc.cpp:?
0x40256965 in ethernet_input_LWIP2 at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/lwip2-src/src/netif/ethernet.c:188
0x40256764 in git2glue_err at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/glue-lwip/lwip-git.c:116
 (inlined by) esp2glue_ethernet_input at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/glue-lwip/lwip-git.c:477
0x402845e5 in ethernet_input at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/glue-esp/lwip-esp.c:365
0x402845f7 in ethernet_input at /home/earle/src/esp-quick-toolchain/arduino/tools/sdk/lwip2/builder/glue-esp/lwip-esp.c:373
0x4027b7a6 in ppPeocessRxPktHdr at ??:?
0x4027fe37 in ets_snprintf at ??:?
0x40105aa5 in call_user_start_local at ??:?

--------------- CUT HERE FOR EXCEPTION DECODER ---------------`
  

</details>

**Microcontroller Specs:**
 - Board: NodeMCU 12 (Lolin)
 - Microcontroller:   ESP8266 
 - Did you modify the partition table? No
 - Browser: Chrome (using Safari the upload bar jumps to 100% and then nothing happens)
 - Library Version: latest

**Comment by emign** [comment]
Damn

**Comment by smeisner** [comment]
I just discovered that in AsyncElegantOTA.h (line 141, definition of the restart() func), it is calling yield() ...and delay() during a callback. I thought this is disallowed by AsyncWebServer! I commented out the call to restart() (line 86 in the AsyncElegantOTAClass definition) and everything works as expected. 

I do need to manually restart my ESP after upload completes. But no crash!

**Comment by hmagarotto** [comment]
I think it's related to the issue: https://github.com/ayushsharma82/AsyncElegantOTA/issues/106 (this issue is still open)
