### ISSUE TITLE
This library is great, I would like to know how to use it in production, like updating hundreds of devices at the same time[BUG] 

### ISSUE THREAD

**Issue by DreamPWJ** [ayushsharma82/AsyncElegantOTA#107]
In most cases, we need to update hundreds of devices at the same time, how to do it?

**Comment by Netexis** [comment]
I have almost the same question, is there a way to use this lib to send binaries thought a script, like sending HTTP request with data to esp/update

**Comment by PockyBum522** [comment]
See this, especially the bottom post in the thread: 
https://github.com/ayushsharma82/AsyncElegantOTA/issues/28
