### ISSUE TITLE
Compile Error ESP32

### ISSUE THREAD

**Issue by pruwait** [ayushsharma82/AsyncElegantOTA#12]
In file included from D:\GoogleDisk\Shared\Arduino\AsyncElegantOTA\AsyncElegantOTA.ino:5:0:

D:\GoogleDisk\Shared\Arduino\libraries\AsyncElegantOTA\src/AsyncElegantOTA.h: In lambda function:

D:\GoogleDisk\Shared\Arduino\libraries\AsyncElegantOTA\src/AsyncElegantOTA.h:50:71: error: 'U_FS' was not declared in this scope

                         int cmd = (filename.indexOf("spiffs") > -1) ? U_FS : U_FLASH;

                                                                       ^

D:\GoogleDisk\Shared\Arduino\libraries\AsyncElegantOTA\src/AsyncElegantOTA.h:51:32: error: 'class UpdateClass' has no member named 'runAsync'

                         Update.runAsync(true);

                                ^

**Comment by ayushsharma82** [comment]
Will be fixing it in a minute.
