### ISSUE TITLE
Cannot upload spiffs.bin

### ISSUE THREAD

**Issue by Derek-K** [ayushsharma82/AsyncElegantOTA#19]
It is a pretty clean design, and I like it. I can upload xxxx.ino.bin without problems, however, I can't seem to be able to upload xxxx.spiffs.bin using the web interface.

I recall in the very original OTA examples (not ElgantOTA), one must stop the SPIFFS before upload spiffs.bin. I wonder if this is the cause of this bug?

**Comment by ayushsharma82** [comment]
Please share your board settings.

**Comment by Derek-K** [comment]
See #21

**Comment by ayushsharma82** [comment]
Fixed with [V2.2.0](https://github.com/ayushsharma82/AsyncElegantOTA/releases/tag/v2.2.0)

Thanks for pointing out that issue!
