### ISSUE TITLE
Cannot upload via ArduinoIDE

### ISSUE THREAD

**Issue by Derek-K** [ayushsharma82/AsyncElegantOTA#20]
When using the original OTA library examples, I can always upload the code via WiFi from ArduinoIDE to an ESP8266.

However, with ElegantOTA, even ArduinoIDE sees the IP under ports, it failed to upload OTA. Any ideas?

**Comment by freeck** [comment]
Arduino uses a different communication protocol i.e. udp (see Python-script: espota.py) .
ElegantOTA uses http-protocol.

**Comment by ayushsharma82** [comment]
ElegantOTA works via HTTP only. You can include both ElegantOTA and ArduinoOTA in a sketch to use both.
