### ISSUE TITLE
ESP 32 does not compile 

### ISSUE THREAD

**Issue by chmasi** [ayushsharma82/AsyncElegantOTA#23]
Hi 

I try to use your Library but it will not compile.

I will get this errormessage

no known conversion for argument 1 from AsyncWebServer to AsyncWebServer*

any suggestion?

Martin

**Comment by barthogenes** [comment]
Hello Martin,

I had the same issue when calling `AsyncElegantOTA.begin(server);`.
The function signature is `void begin(AsyncWebServer *server)` which means that it expects a pointer instead of a copy of the AsyncWebServer variable.
So to start the web server use:
```
AsyncElegantOTA.begin(&server);
```
instead of:
```
AsyncElegantOTA.begin(server);
```

**Comment by chmasi** [comment]
Thanks a lot,
Freundliche Grüsse
Martin Sickel
______________________________________________

Oberdorfstr. 28
78337 Öhningen
+49 7735 3551
martin@die-sickels.de


Am Di., 21. Apr. 2020 um 12:17 Uhr schrieb Bart Hogenes <
notifications@github.com>:
