### ISSUE TITLE
Missing Vue source

### ISSUE THREAD

**Issue by ruohki** [ayushsharma82/AsyncElegantOTA#3]
Hey,

where do we find the source of the vue project?

**Comment by ayushsharma82** [comment]
Will be added in next release.

**Comment by rinkydinkys** [comment]
I don't see why you would release the code in an obfuscated format in the first place, it's pathetic.

**Comment by ayushsharma82** [comment]
Checkout ElegantOTA repository for the Vue source.

This repository is just a fork of it work on AsyncWebServer.

Thanks.
