### ISSUE TITLE
Bug in App.vue

### ISSUE THREAD

**Issue by IAmOrion** [ayushsharma82/AsyncElegantOTA#35]
Missing semi-colon at line 242 which results in build failure unless you use the '--fix' flag

(I've added the semi colon screenshot - it's just to show where it's missing & I added)

<img width="425" alt="Screenshot 2020-09-11 at 01 50 52" src="https://user-images.githubusercontent.com/3501380/92834037-72ebec80-f3d1-11ea-9901-a8660f7da3a8.png">

**Comment by ayushsharma82** [comment]
You can open a pull request in original ElegantOTA repository. Thanks!

**Comment by ayushsharma82** [comment]
Done
