### ISSUE TITLE
Password Hash

### ISSUE THREAD

**Issue by robinschneider** [ayushsharma82/AsyncElegantOTA#43]
The user password for OTA Portal should be hashed using bycrypt or something else rather than plaintext inside the code

**Comment by ayushsharma82** [comment]
@robinschneider 
Good Suggestion. You are invited to be a contributor for AsyncElegantOTA/ElegantOTA.
Let us know if come up with some integration :)

**Comment by Sierra56** [comment]
How to enable password protection?

**Comment by robinschneider** [comment]
It's documented here https://github.com/ayushsharma82/AsyncElegantOTA#additional-security
