### ISSUE TITLE
Couldnt upload sample.json to Filesystem

### ISSUE THREAD

**Issue by isaacncz** [ayushsharma82/AsyncElegantOTA#46]
I tried to upload a sample.json using filesystem, it didnt work. 
![image](https://user-images.githubusercontent.com/49158607/108812990-13824180-75eb-11eb-881f-4046f4a9bdfe.png)
![image](https://user-images.githubusercontent.com/49158607/108813011-1c731300-75eb-11eb-98b0-deb26d306d24.png)

added a few lines to read the SPIFFS.

**Comment by ayushsharma82** [comment]
@isaacncz , Filesystem upload option is not for uploading individual files. It requires a .bin image of complete SPIFFS generated via `mkspiffs` tool. 

You can find more info about that here: https://github.com/igrr/mkspiffs
