### ISSUE TITLE
How is the device id displayed in the ElegantOta webpage is calculated? 

### ISSUE THREAD

**Issue by kanishgsivakumar** [ayushsharma82/AsyncElegantOTA#47]
i am using the last 4 bytes of MAC to compute the device id  but i couldn't figure what method is used here?

**Comment by ayushsharma82** [comment]
This the function that generates your unique device ID: https://github.com/ayushsharma82/AsyncElegantOTA/blob/master/src/AsyncElegantOTA.h#L154

Thanks for using AsyncElegantOTA.
