### ISSUE TITLE
Changing the update path

### ISSUE THREAD

**Issue by arbasel** [ayushsharma82/AsyncElegantOTA#48]
This is not really an issue but rather a feature request. Would it be possible to have a variable that allows us to easily change the update path from /update to something like /otaupdate?

I need /update for something else and tried making manual changes but was unsuccessful.

**Comment by vshumilov** [comment]
Hi, arbasel.
How did you do this variable?

**Comment by arbasel** [comment]
Sorry, I did not know how to do it in ElegantOTA so I changed it instead on my webserver side i.e. left EkegantOTA with update and made my update link something else.

**Comment by ayushsharma82** [comment]
Sadly, Not supported.
