### ISSUE TITLE
Progress Bar goes to 100% due to Antivirus Caching

### ISSUE THREAD

**Issue by mottibz** [ayushsharma82/AsyncElegantOTA#51]
Hello,

1. I am experiencing a strange behavior. I am trying to use this library on an ESP32 using AsyncWebServer.
When I select the file for update (either spiffs or firmware), it starts the OTA immediately and also immediately displays that 100% was done. Then, it takes some time (in which I don't know what is going on as there is no indication) until it shows the success page and then reboots the ESP32. Any suggestion how I can make it work as expected, meaning that the gauge will work as the OTA process executes and will reach 100% only when all is done. Thanks!!!

2. Any way to replace the ElegantOTA logo with something else?

Thanks a lot, Motti

**Comment by ddv2005** [comment]
Hello,

I have the same issue - immediately displays 100% and then update in background.

**Comment by mottibz** [comment]
Hi, No answer yet... Can we get some help? Thanks!

**Comment by ddv2005** [comment]
Looks like I found the problem - antivirus (in my case Kasperskiy). It cache post request into memory and report 100%  immediately.

**Comment by mottibz** [comment]
Interesting... I also use Kaspersky anti virus. I guess that either the AsyncElegantOTA guys overcome this issue or we will need to find another OTA approach...

**Comment by ayushsharma82** [comment]
I'll try implementing the 'chunks' approach in a future release. I hope it will be simple.
