### ISSUE TITLE
How to add login password for AsyncElegantOTA page?

### ISSUE THREAD

**Issue by czweb** [ayushsharma82/AsyncElegantOTA#52]

**Comment by ayushsharma82** [comment]
It's already there in the source code. Please use `AsyncElegantOTA.setAuthentication("username", "password");` function.

**Comment by ayushsharma82** [comment]
Sorry, previous comment was not corresponding to AsyncElegantOTA. Here is the correct solution: `AsyncElegantOTA.begin(&server, "username", "password");`
