### ISSUE TITLE
Do I need AsyncElegantOTA.loop();

### ISSUE THREAD

**Issue by seb201** [ayushsharma82/AsyncElegantOTA#56]
Hello,

in the example you wrote into the void loop() **AsyncElegantOTA.loop();** . But in the Documentation you say, I only need **#include <AsyncElegantOTA.h>** and **AsyncElegantOTA.begin(&server);** before **server.begin();** . What is correct?

**Comment by manhere** [comment]
The function of "AsyncElegantOTA.loop()" is to reboot after the upgrade is completed.

**Comment by haliltaskit** [comment]
After my add to loop this function - my Nodemcu v3 always showed blue light on and didn't allow me to upload new code. Is there someone who have any idea or experience about this ?

**Comment by ayushsharma82** [comment]
Answer provided by @manhere
