### ISSUE TITLE
Hash.h: No such file or directory in Arduino IDE

### ISSUE THREAD

**Issue by mrdc** [ayushsharma82/AsyncElegantOTA#6]
Hello!

I receive an error in Arduino IDE during example compilation: `Hash.h: No such file or directory`.  (https://github.com/ayushsharma82/AsyncElegantOTA/blob/master/examples/ESP32_Async_Demo/ESP32_Async_Demo.ino)
The only `Hash.h` I have is in esp8266 SDK.
Also I receive warnings `Multiple libraries were found for "AsyncTCP.h"`,`Multiple libraries were found for "ESPAsyncWebServer.h"`,`Multiple libraries were found for "AsyncElegantOTA.h"`
How to fix it?

**Comment by ayushsharma82** [comment]
Please refer to https://github.com/me-no-dev/ESPAsyncWebServer/issues/46
