### ISSUE TITLE
No COM connection after enabling OTA

### ISSUE THREAD

**Issue by DanteNahuel** [ayushsharma82/AsyncElegantOTA#62]
Hi,
After I flash the code to my ESP32, the Web Server starts working and I can upload and flash firmware through it, but the device stops showing up as connected through COM ports, no matter what, until I remove the code from it.
I'm lost on where to start to look on what's going on

**Comment by ayushsharma82** [comment]
Weird. This never happened to me.

Let me know if you could find any possible reason to this problem.

**Comment by DanteNahuel** [comment]
I think this was due a misconfiguration on PlatformIO
I can't reproduce it, so I'll close it
Thanks anyway
