### ISSUE TITLE
password protection for /update directory

### ISSUE THREAD

**Issue by mitiay7** [ayushsharma82/AsyncElegantOTA#70]
Dear Sirs, 

Please advise if in current release is possible to protect /update page with password (in ideal word - password should be stored in SPIFF).

Thank you.

Dmitry

**Comment by ayushsharma82** [comment]
Yes, It’s possible to protect webpage. It’s written in ReadMe.

Regards,
Ayush

**Comment by mitiay7** [comment]
Many thanks!
