### ISSUE TITLE
Compile error using current ESP-IDF for ESP32: Hash.h: No such file or directory

### ISSUE THREAD

**Issue by ul-gh** [ayushsharma82/AsyncElegantOTA#8]
Hi,

first, thanks for your nice contribution with this software!

However, the current version ESP-IDF for ESP32 does not contain a "Hash.h" header any more,
compilation fails with "AsyncElegantOTA.h:13:22: fatal error: Hash.h: No such file or directory"

However, the include does not seem to be necessary,
removing the #include "Hash.h" from line no. 13 makes the compilation succeed.

**Comment by finchamp** [comment]
The same issue exists in the current version of Arduino. The same solution applies.

**Comment by ayushsharma82** [comment]
Great. I will test this change and create a pull request.

**Comment by JoeBarouneD** [comment]
Hi, so could you remove the Hash includes in the examples (and in readme) ?

**Comment by smford** [comment]
This problem still exists in the examples

**Comment by ayushsharma82** [comment]
@smford 
With v2.2.1 release, I have added a copy of Hash.h in the `src` folder itself which has fixed that 'missing' error.

Let me know if it still occurs.  Thanks!

**Comment by ayushsharma82** [comment]
@JoeBarouneD  Yeah, I'll do it now, since it is now included in the library itself.

**Comment by ajinkya-open** [comment]
i faced this issue but when i #include<FS.h> its compiling well 

here is snippets

#include <Arduino.h>
#if defined(ESP8266)
#include <ESP8266WiFi.h>
#elif defined(ESP32)
#include <WiFi.h>
#endif

#include <Ticker.h>
#include <ESPAsyncWebServer.h>
#include "fauxmoESP.h"
#include <DNSServer.h>
#include <PubSubClient.h>
#include <AsyncMqtt_Generic.h>
 #include <FS.h> // fs added and has.h error gone
#include <ArduinoJson.h>
#include "config.h"

#include "SPIFFS.h"
extern "C"
{
#include "freertos/FreeRTOS.h"
#include "freertos/timers.h"
}
