### ISSUE TITLE
[ENHANCEMENT] Please allow easy editing of the HTML of the update page.

### ISSUE THREAD

**Issue by ralphrmartin** [ayushsharma82/AsyncElegantOTA#81]
[//]: <> (Please follow this template for fast resolutions)
**Describe the bug**
The update page in the source is provided in an encoded form which is not readily editable.
It would be handy to be able to edit it, to e.g. add further information such as the currently running version of the code, to add warnings about doing the update, etc.
Can the update page please be provided as regular, editable HTML?

**Do you get any error/exception stack? If so please paste it here:**
No.

**Microcontroller Specs:**
Any

**Additional context**

**Comment by 06GitHub** [comment]
Hello ralphrmartin,
Maybe this closed issue **UI Update** can help : https://github.com/ayushsharma82/AsyncElegantOTA/issues/68
ayushsharma82 explains that html page is generated with vuejs, and how to update it (not tested yet on my side)
Regards

**Comment by ralphrmartin** [comment]
Thanks.
