### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by giangi007** [ayushsharma82/AsyncElegantOTA#9]
Hello i receive this error when I try to compile your example for esp32:
Scheda:"WEMOS LOLIN32, 80MHz, Default, 240MHz (WiFi/BT), 115200"

C:\Users\giang\OneDrive\Documenti\Arduino\libraries\Hash\src\Hash.cpp:26:34: fatal error: bearssl/bearssl_hash.h: No such file or directory

compilation terminated.

This is the skecth demo:
#include <WiFi.h>
#include <Hash.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include <AsyncElegantOTA.h>

const char* ssid = "........";
const char* password = "........";

AsyncWebServer server(80);

void setup(void) {
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.println("");

  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
    request->send(200, "text/plain", "Hi! I am ESP32.");
  });

  AsyncElegantOTA.begin(&server);    // Start ElegantOTA
  server.begin();
  Serial.println("HTTP server started");
}

void loop(void) {
  AsyncElegantOTA.loop();
}
Could you help me?

thanks

**Comment by skippa** [comment]
Same issue here, Hash.h isn't found and is throwing compile error... I googled around and all I seem to find is references to PlatformIO issues that throw the same error.

How can we find and include the Hash.h lib?

**Comment by ayushsharma82** [comment]
Please refer to https://github.com/me-no-dev/ESPAsyncWebServer/issues/46
