### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MArimont3** [ayushsharma82/AsyncElegantOTA#93]
This library (is not so elegant as it sounds :-)) and cannot be used inside another library :-(
Probably because it is (badly) written as everything-in-a-.h-file instead of splitting properly .cpp and .h
When AsyncElegantOta.h is included in 2 .cpp files, AsyncElegantOta is instantiated twice, resulting in an error : "(.bss.AsyncElegantOTA+0x0): multiple definition of `AsyncElegantOTA'"
If it is included in just one .cpp file in another library, I get the error "'Update.h' cannot be found"

**Comment by ayushsharma82** [comment]
Fixed with #95  :)
